from dataclasses import dataclass
from typing import Any, Dict, Optional, Tuple


@dataclass
class FenceEvent:
    """
    Standard IBVAP physical fence security event.

    This event is generated by the ML layer after
    a fence abnormality has been confirmed.
    """

    event_type: str

    breach_type: str

    confidence: float

    severity: str

    camera_id: Optional[str] = None

    bbox: Optional[Tuple[int, int, int, int]] = None

    track_id: Optional[int] = None

    reason: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the event into a JSON-compatible
        dictionary.
        """

        return {
            "event_type": self.event_type,
            "breach_type": self.breach_type,
            "confidence": self.confidence,
            "severity": self.severity,
            "camera_id": self.camera_id,
            "bbox": self.bbox,
            "track_id": self.track_id,
            "reason": self.reason,
        }


class FenceEventGenerator:
    """
    Converts confirmed fence analysis results
    into standardized IBVAP events.
    """

    EVENT_TYPE = "FENCE_BREACH"

    ACTIVE_BREACH = {
        "CLIMBING",
        "CROSSING",
        "CUTTING",
        "BREAKING",
    }

    DAMAGE_TYPES = {
        "CUT",
        "BROKEN",
        "DAMAGED",
        "MISSING_SECTION",
    }

    def generate(
        self,
        breach_type: str,
        confidence: float,
        severity: str,
        camera_id: Optional[str] = None,
        bbox: Optional[
            Tuple[int, int, int, int]
        ] = None,
        track_id: Optional[int] = None,
        reason: Optional[str] = None,
    ) -> FenceEvent:
        """
        Generate one standardized fence event.
        """

        breach_type = breach_type.upper()

        if breach_type in self.DAMAGE_TYPES:
            event_type = "FENCE_DAMAGE"
        else:
            event_type = self.EVENT_TYPE

        return FenceEvent(
            event_type=event_type,
            breach_type=breach_type,
            confidence=float(confidence),
            severity=severity.upper(),
            camera_id=camera_id,
            bbox=bbox,
            track_id=track_id,
            reason=reason,
        )